
CUSTOM_TAG_PATTERN = /custom-v(\d+)/
CUSTOM_BRANCH_NAME = 'master_custom'
LIGHT_BRANCH_NAME = 'master_custom_light'

CUSTOM_BACKUP_BRANCH_NAME = "#{CUSTOM_BRANCH_NAME}_backup"
LIGHT_BACKUP_BRANCH_NAME = "#{LIGHT_BRANCH_NAME}_backup"
